apiVersion: 1

datasources:
  - name: SwarmInfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: swarm
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: swarm-admin-token
    editable: true
